CREATE TABLE PRICES
(
    id         INTEGER      NOT NULL AUTO_INCREMENT,
    BRAND_ID   NUMBER       NOT NULL,
    START_DATE DATETIME     NOT NULL,
    END_DATE   DATETIME     NOT NULL,
    PRICE_LIST NUMBER       NOT NULL,
    PRODUCT_ID NUMBER       NOT NULL,
    PRIORITY   NUMBER       NOT NULL,
    PRICE      NUMBER       NOT NULL,
    CURRENCY   VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);